name: CI - Build, Test, Image & Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image (make available locally)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: iric-app:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: iric-app:latest
          format: 'table'
          exit-code: 1
          severity: "CRITICAL,HIGH"
